---
title: "**Resume**"
output: 
  html_document:
    toc: false
    toc_float: false
    theme: cosmo
---


### Contact Information {.tabset}

<font size="4">Email: cl4045@cumc.columbia.edu

#### Education

##### **<font size="4">Columbia University, Mailman School of Public Health** *New York, NY</font>*
*<font size="4">May 2022, Master of Science (MS), Biostatistics, Theory and Method Track, 3.87</font>*\			

* <font size="4">*Relevant Coursework*: Biostatistics I & II, Data Science I & II, Probability, Statistical Inference, Latent Variable Model</font>

##### **<font size="4">New York University Leonard N. Stern School of Business** *New York, NY</font>*
*<font size="4">May 2020, Bachelor of Science (BS), Econometrics, minors in Psychology and Advance Mathematical Methods, 3.64</font>*\

* <font size="4">*Relevant coursework*: Mathematics for Economics I,II & III, Linear Algebra, Numerical Analysis, Macroeconomic Foundations for Asset Prices, Game Theory, Intro to Computer Science, The Financial System</font>

##### **<font size="4">The Hotchkiss School** *Lakeville, CT</font>*
*<font size="4">May 2016, General secondary education</font>*\

* <font size="4">Coeducational preparatory school in Lakeville, Connecticut, United States</font>

#### Research Experiences

##### **<font size="4">Columbia University Center for Statistical Genetics** *New York, NY*
*<font size="4">Research Assistant (Summer 2021)*\

*	<font size="4">Cleaning and filtering WES Alzheimer’s disease patient data in R</font>
* <font size="4">Updating and debugging parametric linkage analysis software (SEQLinkage) in Python</font>
* <font size="4">Conducting genetic mapping analysis with patient genotype data using container images at remote cluster</font>

##### **<font size="4">Prof. Kilduff at NYU Stern School of Business** *New York, NY*
*<font size="4">Research Coordinator (Fall 2018 - Fall 2019)*\

* <font size="4">Conducted research on the link between career outcomes and childhood/adolescent adversity
*	<font size="4">Managed and oversaw experiments with paid participants at Stern’s Center of Behavioral Research
* <font size="4">Coordinated group studies with on-campus organizations to investigate Prof. Kilduff’s hypothesis that individuals’ work performance positively correlates with their ability to discern social hierarchy

#### Work Experiences

##### **<font size="4">Tongyuan Capital** *Shanghai,China*
*<font size="4">Summer Analyst (Summer 2017)*\

*	<font size="4">Conducted market research at multiple electric vehicle investor conferences as firm representative
*	<font size="4">Gathered data on United States equity market conditions for daily briefings to supervising executives

##### **<font size="4">Shanghaiist** *Shanghai,China*
*Editorial Intern (Summer 2016)*\

*	Wrote briefings on geopolitics including United States presidential election and South China Sea Arbitration 
*	Assisted editor-in-chief in drafting weekly frontpage reports on local sporting event

##### **<font size="4">Human Resources Intern** *Shanghai,China*
*Human Resources Intern (Summer 2015)*\

* Designed and implemented a competition-oriented training program for 50+ manufacturing technicians to sufficiently acquire needed GMP (Good Manufacturing Practice) knowledge

#### Other Experiences

##### **<font size="4">Neuromatch Academy**
*Summer 2020*\

*	Collaborated with other researchers remotely to analyze Steinmetz mice behavior data

##### **<font size="4">Fed Challenge Team** 
*Fall 2019*\

*	Represented NYU Stern at the Fed Challenge, an annual academic competition on monetary policy held by Federal Reserve 

##### **<font size="4">Stern Political Economy Exchange** 
*Spring 2018 - Fall 2020*\

* Served on executive board leadership for student club focuses on intersection of economics and geopolitics
